#Minecraft server properties
#Mon Sep 07 02:06:51 EDT 2026
#Specific config tied to running this on my local machine without external access
allow-flight=false
allow-nether=true
level-name=MyServer
level-seed=JASON
max-players=1
online-mode=false
pvp=true
server-ip=127.0.0.1
server-port=5560
spawn-animals=true
spawn-monsters=true
view-distance=10
white-list=false
